version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./containers/api/Dockerfile
      target: local
    depends_on:
      - mysql
    volumes:
      - ./src:/src
    env_file:
      - ./.env
    ports:
      - "8006:8000"
    tty: true
  mysql:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 5s
      retries: 20
    image: mysql:8.0
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./containers/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "33060:3306"
    env_file:
      - ./containers/mysql/.env
    command: --default-authentication-plugin=mysql_native_password
